eclipse-edc/.github

profile/README.md
Updates link to developer documentation
Relative links don't seem to work with GitHub profiles
=> fix(profile): update link to developer documentation

.github/dependabot.yml
Adds dependabot.yml
Closes #47 
=> feat: add dependabot.yml file

.github/actions/bump-version/action.yml, .github/actions/run-tests/action.yml, .github/actions/setup-build/action.yml, .github/release.yaml, .github/workflows/add-to-project.yml, .github/workflows/bump-version.yaml, .github/workflows/close-inactive-issues.yml, .github/workflows/discord-webhook.yml, .github/workflows/first-interaction.yml
Adds actions and workflows as-is:
- `./actions`
- `add-to-project`
- `bump-version`
- `close-inactive-issues`
- `discord-webhook`
- `first-interaction`
- `release`
Added dependency categorie to release notes.
Enhance maintenance
Workflows need to be removed from other repos step-by-step.
`trigger_snapshot` and `release-edc` will follow in another PR
Relates eclipse-edc/Connector#3033
=> feat: add basic workflows from connector repo

.github/workflows/dependency-check.yml
Adds a workflow, that:
- checks for allowed licenses in all dependencies
- verifies that the DEPENDENCIES file is still up to date and does not contain any `rejected` libs
Compliance with Eclipse
- the same workflow file, and an initial DEPENDENCIES file will be added to all existing repos.
=> feat(ci): add DEPENDENCIES check workflow

.github/workflows/discord-webhook.yml, .github/workflows/first-interaction.yml, .github/workflows/scan-pull-request.yml, .github/workflows/stale-bot.yml, contributing/pr_etiquette.md
Following the GitHub documentation, we can use [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) to enhance the maintenance of workflows. The workflows will be placed in this repo and referenced from workflow files in the other repos. This way, workflow changes will automatically apply to all repos. 
Enhance maintenance
=> feat: add reusable workflows

.github/workflows/dependency-check.yml
Ignore `diff` exit status
print the correct DEPENDENCIES file 
=> fix: print dependencies file on failure

.github/workflows/dependency-check.yml
use an absolute path for the `setup-build` action.
some repos, that use the `dependency-check` workflow might not necessarily have the `setup-build` action defined, so it should be referenced with an absolute path.
=> chore: use setup-build action with absolute path

.github/actions/import-gpg-key/action.yml, .github/workflows/_trigger-snapshot.yml, .github/workflows/publish-snapshot.yml, .github/workflows/trigger-snapshot.yml
Adds a base workflow (and action) so that EDC projects can directly publish to Sonatype Snapshots from GHA.
Avoid going to Jenkins
- Once this is merged, we can update all the `trigger-snapshot.yaml` files in all the components, so that they actually invoke this workflow here.
- successful run: https://github.com/eclipse-edc/Runtime-Metamodel/actions/runs/6170964283/job/16748285538
Closes #https://github.com/eclipse-edc/.github/issues/71
=> feat(build): publish to OSSRH Snapshots and MavenCentral from GHA

.github/workflows/bump-version.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/release-component.yml
Adds absolute reference to .github workflows & actions
Relative references are failing (see https://github.com/eclipse-edc/Template-Basic/pull/2) when run in an external repo. Seems like this has been missed in #63.
=> fix: add absolute reference to .github workflows & actions

.github/workflows/publish-snapshot.yml
Fix the `grep` expression to extract the project version, from `version:` to `version: ` with a trailing colon, this because now in `Connector` we have modules that contains the `version:` string in path.
failing workflow example: https://github.com/eclipse-edc/Connector/actions/runs/8017082606/job/21900245378
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for …
=> build: fix version extraction

.github/actions/bump-version/action.yml, .github/actions/run-tests/action.yml, .github/actions/setup-build/action.yml
bumps action dependencies in reusable actions
looks like dependabot skipped them
=> build(deps): bump reusable actions

.github/workflows/publish-openapi-ui.yml
Add a reusable workflow that, given the list of `api_groups` in input, generates openapi, generates swagger ui sites and deploy them on the repository github pages with the following url:
`https://<org>.github.io/<repo-name>/openapi/<api-group>/<version>`
if the version is not snapshot (e.g. for stable releases, the ui will be also published at:
`https://<org>.github.io/<repo-name>/openapi/<api-group>`
openapi spec availability
- the workflow is divided in 3 jobs:
1. generate openapi spec by calling `./gradlew resolve` and upload the produced artifacts
2. download the specs and merge them for every `api-group`, generate "version" ui and, in the case of a non snapshot version, generate also one without version (a `cp` would have been enough but also generating them takes no time). Upload …
=> build: reusable workflow for build and upload openapi spec ui to github pages

.github/workflows/publish-autodoc.yml
Reusable workflow to publish autodoc output to github pages
documentation
=> build: publish autodoc output on github pages workflow

.github/workflows/publish-autodoc.yml
use the new `doc2html` renderer to create html documentation.
=> build: use doc2html for publishing autodoc

.github/workflows/publish-autodoc.yml, .github/workflows/publish-openapi-ui.yml
According to the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call), the `github.event` refers to the event that started the caller workflow, instead `inputs` refers to the actual parameters passed
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull …
=> build: get version from inputs not from the starting event

.github/workflows/publish-openapi-ui.yml
For openapi publication: get version from the `version.json` file if it exists
- at this point the inputs.version is not necessary anymore, because at every commit the new version of the api context will be published.
Part of https://github.com/eclipse-edc/Connector/issues/4182
=> build(docs): get openapi version from .version file if it exists

.github/workflows/publish-openapi-ui.yml, .github/workflows/verify-openapi.yml
Adds reusable workflow to verify openapi spec changes (if they changes, also the `version.json` file needs to)
- improve the `publish-openapi-ui.yml` flow as well
=> build(docs): add reusable verify openapi workflow

.github/workflows/publish-openapi-ui.yml, .github/workflows/verify-openapi.yml
Selects stable api version to use for openapi publishing/verification
Closes #124 
=> docs: select stable version for publish/verifying openapi specs

.github/actions/bump-version/action.yml
As discussed, it makes the `bump-version` action bump the minor version number, while the patch version number is set to 0. 
This is the behavior we want to achieve on every "standard" release (where new features will be provided). For hotfix releases the process is still manual, but they should not definitely bump the snapshot version.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) …
=> build: bump minor version number on release

.github/workflows/verify-bom.yml
creates a centralized workflow to verify runnable BOM modules
avoid code duplication. this WF can be used by the connector, FC and IH repos (And others)
=> feat(ci): add workflow to verify BOMs

.github/workflows/technology-release.yml
Merged the `Publish-Artefacts` and `Create-Tag` into a single `Release` job, that, in order, sets the version, publishes artifacts and creates tag
=> ci: technology release: change version before publishing artifacts

.github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
updates the issue template adding the "Sponsor" section as per committer discussion of Jan 22nd, 2025
=> chore: update issue template
